spring:
  application:
    name: spring-cloud-client-one
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true